site_name: Offline Function Calling with Gemma
site_url: https://offline-function-calling.github.io/
theme:
  name: shadcn
  icon: streamline:ai-chip-spark
  pygments_style: github-dark
  custom_dir: docs/theme/

repo_url: https://github.com/offline-function-calling/sdk
edit_uri: edit/main/docs/

nav:
  - Overview: index.md
  - Setup:
    - Tools: setup/tools.md
    - Models: setup/models.md
  - Learn:
    - Hello, Function Calling!: learn/hello-world.md
    - Structuring and Scaling: learn/structuring-and-scaling.md
    - Dynamic Function Generation: learn/dynamic-function-generation.md
    - Multimodal Input: learn/multimodal-input.md
  - Benchmarks:
    - Methodology: bench/methodology.md
    - Leaderboard: bench/leaderboard.md
    - Datasets and Code: bench/datasets-and-code.md

plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
